### ISSUE TITLE
Add a note count overwrite to the YAML section

### ISSUE THREAD

**Issue by JackGruber** [JackGruber/joplin-plugin-note-overview#17]
```
notecount:
  - disable:
  - prefix:
  - suffix:
  - position:
```

- Add prefix / suffix as to the option screen?
