### ISSUE TITLE
Add filter for body / excerpt

### ISSUE THREAD

**Issue by JackGruber** [JackGruber/joplin-plugin-note-overview#27]
Add filter for body / excerpt
```
match:
    regexp:
        - XYZ
        - ABC
    todo:
        done: true
        open: true
```
