### ISSUE TITLE
Add notes count to details summary line 

### ISSUE THREAD

**Issue by MHoeller** [JackGruber/joplin-plugin-note-overview#36]
### Story
As a user I want to see the count of notes it a details summary line when the summary is not opened, so that I can see if the filter returns content without opening the details

#### Code
```
<!-- note-overview-plugin
search: -tag:*
fields: title
details:
  open: false
  summary: All notes without a Tag  - **Notes count {{ count }}**
-->
```

#### Result
All notes without a Tag  - **Notes count 42**
