### ISSUE TITLE
Conflicts [24] with 3 Joplins

### ISSUE THREAD

**Issue by jlpoolen** [JackGruber/joplin-plugin-note-overview#75]
I'm running Joplin on three machines, 2 Linux and 1 Win7.  The Win7, of course, may be the problem child here, the version of Joplin on Win7 is:
```
Joplin 2.12.5 (prod, win32)

Client ID: 9c3420e08da64b508e4db00852700d74
Sync Version: 3
Profile Version: 43
Keychain Supported: Yes

Revision: 7c4b122

CodePerfect: 1.0.2
Csv Import: 1.0.1
Font Size Shortcut: 1.0.0
Math Mode: 0.7.1
Text Colorize: 1.2.5
```
On the Win7 desktop, I'm getting 24 conflicts in a test page that has the following:

```
Title: Testing Noteoverview
The Plug-in Note Overview at
https://github.com/JackGruber/joplin-plugin-note-overview
Below here is a tag that is suppose to retrieve stuff with Humanized time
<!-- note-overview-plugin
search: -tag:*
fields: updated_time, title
alias: updated_time AS Last edit, title AS Title
sort: title DESC
datetime:
  date: YYYY-MM-DD
  time: HH:mm
  humanize:
    enabled:
      - true | false
    withSuffix:
      - true | false
-->
```
![Joplin_2024-10-23_16-11-09](https://github.com/user-attachments/assets/a9b79f5a-2ef5-4cc5-9261-c6d0b28226e5)
My other desktops:

```
Linux Desktop: (has 3 conflicts, two are Testing Note Overview)

Joplin 3.0.15 (prod, linux)

Client ID: eb42cb5b020a40c69826759ddc02a435
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: 598677b

Backup: 1.4.1
Chat GPT Search: 1.0.0
CodePerfect: 1.0.2
Csv Import: 1.0.1
Markdown Table: Colorize: 1.2.0
Math Mode: 0.7.1
Text Colorize: 1.2.5

Linux Laptop: ( no conflicts) 

Joplin 3.0.15 (prod, linux)

Client ID: c3566459b62f4707b871a775a742baa9
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: 598677b

Backup: 1.4.1
Note overview: 1.7.1
```

Suggestions, or do we deem Joplin 2.12.5 (prod, win32) in compatible?  Can and should I configure the Note-overview page to not be replicated?  Should I have Note-overview installed in all instances of Joplin?
